// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5YJDq04ThmXM8_tb7TrEp2YyjunemZFw',
    appId: '1:121766139808:web:561ad5b059519b79a476c5',
    messagingSenderId: '121766139808',
    projectId: 'ticket-hub-b9258',
    authDomain: 'ticket-hub-b9258.firebaseapp.com',
    storageBucket: 'ticket-hub-b9258.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjoGJNCWpQNvESGZFrPgl9fCC2CZRlVxE',
    appId: '1:121766139808:android:c8b2d446cc93e209a476c5',
    messagingSenderId: '121766139808',
    projectId: 'ticket-hub-b9258',
    storageBucket: 'ticket-hub-b9258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsdQS43BAdb5CgozhWS2M-sgfLi-lLq8',
    appId: '1:121766139808:ios:0706df4397a4f896a476c5',
    messagingSenderId: '121766139808',
    projectId: 'ticket-hub-b9258',
    storageBucket: 'ticket-hub-b9258.appspot.com',
    iosBundleId: 'com.example.ticketHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSsdQS43BAdb5CgozhWS2M-sgfLi-lLq8',
    appId: '1:121766139808:ios:0706df4397a4f896a476c5',
    messagingSenderId: '121766139808',
    projectId: 'ticket-hub-b9258',
    storageBucket: 'ticket-hub-b9258.appspot.com',
    iosBundleId: 'com.example.ticketHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5YJDq04ThmXM8_tb7TrEp2YyjunemZFw',
    appId: '1:121766139808:web:a36dd2ca227f8bc1a476c5',
    messagingSenderId: '121766139808',
    projectId: 'ticket-hub-b9258',
    authDomain: 'ticket-hub-b9258.firebaseapp.com',
    storageBucket: 'ticket-hub-b9258.appspot.com',
  );
}
